services:
  db:
    image: postgres:15-alpine
    container_name: status_tracker_bot_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: status_bot
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - TZ=Asia/Yekaterinburg
      - DB_URL=host=${DB_HOST} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} sslmode=disable

volumes:
  pg_data:
